"""State keys for the Depreciation Run Wizard."""
KEY_RUN_DATE = "run_date"
KEY_PERIOD_END_DATE = "period_end_date"
KEY_RUN_ID = "run_id"
KEY_RUN_NUMBER = "run_number"
KEY_RUN_STATUS = "run_status"
KEY_ASSET_COUNT = "asset_count"
KEY_TOTAL_DEPRECIATION = "total_depreciation"
KEY_POST_CONFIRMED = "post_confirmed"
KEY_POSTED_JOURNAL_ENTRY_ID = "posted_journal_entry_id"
