"""State keys for the New Customer Wizard."""
KEY_CUSTOMER_CODE = "customer_code"
KEY_DISPLAY_NAME = "display_name"
KEY_LEGAL_NAME = "legal_name"
KEY_CUSTOMER_GROUP_ID = "customer_group_id"
KEY_PHONE = "phone"
KEY_EMAIL = "email"
KEY_ADDRESS_LINE_1 = "address_line_1"
KEY_ADDRESS_LINE_2 = "address_line_2"
KEY_CITY = "city"
KEY_REGION = "region"
KEY_COUNTRY_CODE = "country_code"
KEY_PAYMENT_TERM_ID = "payment_term_id"
KEY_TAX_IDENTIFIER = "tax_identifier"
KEY_CREDIT_LIMIT_AMOUNT = "credit_limit_amount"
KEY_NOTES = "notes"
KEY_CUSTOMER_ID = "customer_id"
