"""State keys for the Supplier Payment Wizard."""
KEY_SUPPLIER_ID = "supplier_id"
KEY_SUPPLIER_NAME = "supplier_name"
KEY_FINANCIAL_ACCOUNT_ID = "financial_account_id"
KEY_FINANCIAL_ACCOUNT_NAME = "financial_account_name"
KEY_FINANCIAL_ACCOUNT_CURRENCY = "financial_account_currency"
KEY_PAYMENT_DATE = "payment_date"
KEY_CURRENCY_CODE = "currency_code"
KEY_AMOUNT_PAID = "amount_paid"
KEY_REFERENCE_NUMBER = "reference_number"
KEY_NOTES = "notes"
KEY_ALLOCATIONS = "allocations"  # list[{"bill_id", "bill_number", "open_balance", "allocated"}]
KEY_TOTAL_ALLOCATED = "total_allocated"
KEY_POST_NOW = "post_now"
KEY_PAYMENT_ID = "payment_id"
KEY_PAYMENT_NUMBER = "payment_number"
KEY_PAYMENT_STATUS = "payment_status"
KEY_POSTED_JOURNAL_ENTRY_ID = "posted_journal_entry_id"
