"""State keys for the Bank Reconciliation Wizard."""
KEY_FINANCIAL_ACCOUNT_ID = "financial_account_id"
KEY_FINANCIAL_ACCOUNT_NAME = "financial_account_name"
KEY_STATEMENT_END_DATE = "statement_end_date"
KEY_STATEMENT_ENDING_BALANCE = "statement_ending_balance"
KEY_NOTES = "notes"
KEY_SESSION_ID = "session_id"
KEY_SESSION_STATUS = "session_status"
KEY_TOTAL_MATCHED = "total_matched"
KEY_MATCHED_COUNT = "matched_count"
KEY_UNMATCHED_COUNT = "unmatched_count"
KEY_FINALIZE_CONFIRMED = "finalize_confirmed"
