from __future__ import annotations

"""
Offline Ed25519 license key validator.

Key format
----------
``SEEKER-{base64url_no_padding}``

The raw bytes after decoding are:
  [0]      edition : uint8   — always 1 for "standard"
  [1..4]   issued_at: uint32 big-endian — Unix timestamp (UTC)
  [5..8]   expires_at: uint32 big-endian — Unix timestamp (UTC)
  [9..16]  nonce    : 8 bytes random

Total payload: 17 bytes.

The Ed25519 signature (64 bytes) is appended directly:
  bytes[0:17]  — payload
  bytes[17:81] — Ed25519 signature over the 17-byte payload

Encoded length: ceil(81 / 3) * 4 = 108 base64url chars (no padding)
Total key string: "SEEKER-" + 108 chars = 115 chars

The Ed25519 *public* key is embedded below.  The private key is held by
the vendor offline.  Knowing the public key is completely safe — it cannot
be used to forge new license keys.
"""

import base64
import datetime
import struct
from dataclasses import dataclass

# ── Embedded Ed25519 public key (32 bytes) ────────────────────────────────────
# Generated by: scripts/generate_license_keypair.py
# Private key is held by the vendor offline.
# Knowing the public key is completely safe — it cannot be used to forge keys.
_PUBLIC_KEY_BYTES: bytes | None = bytes.fromhex(
    "f4bdebd8d6980a48957acf6ee5e0fe03d94f57d2adcf1fb9c3498e8185bce2d2"
)


_KEY_PREFIX = "SEEKER-"
_PAYLOAD_SIZE = 17  # bytes
_SIGNATURE_SIZE = 64  # bytes (Ed25519)
_RAW_SIZE = _PAYLOAD_SIZE + _SIGNATURE_SIZE  # 81 bytes
_EDITION_STANDARD = 1


@dataclass(frozen=True, slots=True)
class LicensePayload:
    edition: int
    issued_at: datetime.date
    expires_at: datetime.date


class LicenseKeyValidator:
    """Validates Ed25519-signed offline license keys."""

    def __init__(self, public_key_bytes: bytes | None = None) -> None:
        self._public_key_bytes = public_key_bytes or _PUBLIC_KEY_BYTES

    def validate(self, key_string: str) -> LicensePayload:
        """
        Validate *key_string* and return the decoded payload.

        Raises ``ValueError`` with a user-facing message if the key is
        syntactically invalid, has a bad signature, or if no public key is
        configured.
        """
        if self._public_key_bytes is None:
            raise ValueError(
                "No license public key is configured. "
                "The application cannot validate license keys."
            )

        key_string = key_string.strip()
        if not key_string.upper().startswith(_KEY_PREFIX.upper()):
            raise ValueError("Invalid license key format.")

        encoded = key_string[len(_KEY_PREFIX):]
        try:
            # base64url without padding
            padding = (4 - len(encoded) % 4) % 4
            raw = base64.urlsafe_b64decode(encoded + "=" * padding)
        except Exception:
            raise ValueError("License key contains invalid characters.")

        if len(raw) != _RAW_SIZE:
            raise ValueError("License key has unexpected length.")

        payload_bytes = raw[:_PAYLOAD_SIZE]
        signature_bytes = raw[_PAYLOAD_SIZE:]

        self._verify_signature(payload_bytes, signature_bytes)
        return self._decode_payload(payload_bytes)

    def _verify_signature(self, payload_bytes: bytes, signature_bytes: bytes) -> None:
        try:
            from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
        except ImportError:
            raise ValueError(
                "The 'cryptography' package is required for license validation. "
                "Please reinstall the application."
            )

        try:
            public_key = Ed25519PublicKey.from_public_bytes(self._public_key_bytes)  # type: ignore[arg-type]
            public_key.verify(signature_bytes, payload_bytes)
        except Exception:
            raise ValueError("License key signature is invalid. The key may be corrupted or forged.")

    @staticmethod
    def _decode_payload(payload_bytes: bytes) -> LicensePayload:
        edition, issued_ts, expires_ts, _nonce = struct.unpack("!BII8s", payload_bytes)
        issued_at = datetime.date.fromtimestamp(issued_ts)
        expires_at = datetime.date.fromtimestamp(expires_ts)
        return LicensePayload(
            edition=edition,
            issued_at=issued_at,
            expires_at=expires_at,
        )


def set_public_key(public_key_bytes: bytes) -> None:
    """Override the embedded public key at runtime (for testing)."""
    global _PUBLIC_KEY_BYTES  # noqa: PLW0603
    _PUBLIC_KEY_BYTES = public_key_bytes
