"""State keys for the Receipt Allocation Wizard."""
KEY_CUSTOMER_ID = "customer_id"
KEY_CUSTOMER_NAME = "customer_name"
KEY_FINANCIAL_ACCOUNT_ID = "financial_account_id"
KEY_FINANCIAL_ACCOUNT_NAME = "financial_account_name"
KEY_FINANCIAL_ACCOUNT_CURRENCY = "financial_account_currency"
KEY_RECEIPT_DATE = "receipt_date"
KEY_CURRENCY_CODE = "currency_code"
KEY_AMOUNT_RECEIVED = "amount_received"
KEY_REFERENCE_NUMBER = "reference_number"
KEY_NOTES = "notes"
KEY_ALLOCATIONS = "allocations"  # list[{"invoice_id": int, "invoice_number": str, "open_balance": str, "allocated": str}]
KEY_TOTAL_ALLOCATED = "total_allocated"
KEY_POST_NOW = "post_now"
KEY_RECEIPT_ID = "receipt_id"
KEY_RECEIPT_NUMBER = "receipt_number"
KEY_RECEIPT_STATUS = "receipt_status"
KEY_POSTED_JOURNAL_ENTRY_ID = "posted_journal_entry_id"
