"""
Comprehensive audit: compare backup_merge_service.py column lists against actual DB schema.
Detects:
  - columns in merge but NOT in DB (will cause INSERT failures)
  - columns in DB but NOT in merge (data loss on import)
  - FK columns not being remapped (dangling references after import)
"""

# ===== ACTUAL DB SCHEMA (from PRAGMA table_info) ===========================
DB_SCHEMA = {
    "permissions": ['id', 'code', 'name', 'module_code', 'description'],
    "roles": ['id', 'code', 'name', 'description', 'is_system', 'created_at', 'updated_at'],
    "role_permissions": ['role_id', 'permission_id'],
    "users": ['id', 'username', 'display_name', 'email', 'password_hash', 'last_login_at', 'created_at', 'updated_at', 'is_active', 'must_change_password', 'avatar_storage_path', 'avatar_original_filename', 'avatar_content_type', 'avatar_sha256', 'avatar_updated_at', 'password_changed_at'],
    "companies": ['id', 'legal_name', 'display_name', 'registration_number', 'tax_identifier', 'phone', 'email', 'website', 'address_line_1', 'address_line_2', 'city', 'region', 'country_code', 'base_currency_code', 'created_at', 'updated_at', 'is_active', 'sector_of_operation', 'logo_storage_path', 'logo_original_filename', 'logo_content_type', 'logo_sha256', 'logo_updated_at', 'deleted_at', 'cnps_employer_number'],
    "company_preferences": ['company_id', 'date_format_code', 'number_format_code', 'decimal_places', 'tax_inclusive_default', 'allow_negative_stock', 'default_inventory_cost_method', 'updated_at', 'updated_by_user_id', 'idle_timeout_minutes', 'password_expiry_days'],
    "company_fiscal_defaults": ['company_id', 'fiscal_year_start_month', 'fiscal_year_start_day', 'default_posting_grace_days', 'updated_at'],
    "company_project_preferences": ['company_id', 'allow_projects_without_contract', 'default_budget_control_mode_code', 'default_commitment_control_mode_code', 'budget_warning_percent_threshold', 'require_job_on_cost_posting', 'require_cost_code_on_cost_posting', 'updated_at', 'updated_by_user_id'],
    "user_company_access": ['id', 'user_id', 'company_id', 'role_scope_note', 'is_default_company', 'granted_at', 'granted_by_user_id'],
    "user_roles": ['user_id', 'role_id'],
    "payment_terms": ['id', 'company_id', 'code', 'name', 'days_due', 'description', 'is_active'],
    "tax_codes": ['id', 'company_id', 'code', 'name', 'tax_type_code', 'calculation_method_code', 'rate_percent', 'is_recoverable', 'effective_from', 'effective_to', 'created_at', 'updated_at', 'is_active'],
    "document_sequences": ['id', 'company_id', 'document_type_code', 'prefix', 'suffix', 'next_number', 'padding_width', 'reset_frequency_code', 'created_at', 'updated_at', 'is_active'],
    "accounts": ['id', 'company_id', 'account_code', 'account_name', 'account_class_id', 'account_type_id', 'parent_account_id', 'normal_balance', 'allow_manual_posting', 'is_control_account', 'notes', 'created_at', 'updated_at', 'is_active'],
    "account_role_mappings": ['id', 'company_id', 'role_code', 'account_id', 'updated_at'],
    "tax_code_account_mappings": ['id', 'company_id', 'tax_code_id', 'sales_account_id', 'purchase_account_id', 'tax_liability_account_id', 'tax_asset_account_id', 'updated_at'],
    "ias_income_statement_templates": ['id', 'statement_profile_code', 'template_code', 'template_title', 'description', 'standard_note', 'display_order', 'row_height', 'section_background', 'subtotal_background', 'statement_background', 'amount_font_size', 'label_font_size', 'created_at', 'updated_at', 'is_active'],
    "ias_income_statement_sections": ['id', 'statement_profile_code', 'section_code', 'section_label', 'parent_section_code', 'display_order', 'row_kind_code', 'is_mapping_target', 'created_at', 'updated_at', 'is_active'],
    "ias_income_statement_mappings": ['id', 'company_id', 'statement_profile_code', 'section_code', 'subsection_code', 'account_id', 'sign_behavior_code', 'display_order', 'created_by_user_id', 'updated_by_user_id', 'created_at', 'updated_at', 'is_active'],
    "ias_income_statement_preferences": ['company_id', 'template_code', 'updated_at', 'updated_by_user_id'],
    "fiscal_years": ['id', 'company_id', 'year_code', 'year_name', 'start_date', 'end_date', 'status_code', 'created_at', 'updated_at', 'is_active'],
    "fiscal_periods": ['id', 'company_id', 'fiscal_year_id', 'period_number', 'period_code', 'period_name', 'start_date', 'end_date', 'status_code', 'is_adjustment_period', 'created_at', 'updated_at'],
    "journal_entries": ['id', 'company_id', 'fiscal_period_id', 'entry_number', 'entry_date', 'journal_type_code', 'reference_text', 'description', 'source_module_code', 'source_document_type', 'source_document_id', 'status_code', 'posted_at', 'posted_by_user_id', 'created_by_user_id', 'created_at', 'updated_at', 'transaction_date'],
    "journal_entry_lines": ['id', 'journal_entry_id', 'line_number', 'account_id', 'line_description', 'debit_amount', 'credit_amount', 'created_at', 'updated_at', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id'],
    "customer_groups": ['id', 'company_id', 'code', 'name', 'created_at', 'updated_at', 'is_active'],
    "customers": ['id', 'company_id', 'customer_code', 'display_name', 'legal_name', 'customer_group_id', 'payment_term_id', 'tax_identifier', 'phone', 'email', 'address_line_1', 'address_line_2', 'city', 'region', 'country_code', 'credit_limit_amount', 'notes', 'created_at', 'updated_at', 'is_active'],
    "sales_invoices": ['id', 'company_id', 'invoice_number', 'customer_id', 'invoice_date', 'due_date', 'currency_code', 'exchange_rate', 'status_code', 'payment_status_code', 'reference_number', 'notes', 'subtotal_amount', 'tax_amount', 'total_amount', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at', 'contract_id', 'project_id'],
    "sales_invoice_lines": ['id', 'sales_invoice_id', 'line_number', 'description', 'quantity', 'unit_price', 'discount_percent', 'discount_amount', 'tax_code_id', 'revenue_account_id', 'line_subtotal_amount', 'line_tax_amount', 'line_total_amount', 'created_at', 'updated_at', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id'],
    "customer_receipts": ['id', 'company_id', 'receipt_number', 'customer_id', 'financial_account_id', 'receipt_date', 'currency_code', 'exchange_rate', 'amount_received', 'status_code', 'reference_number', 'notes', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at'],
    "customer_receipt_allocations": ['id', 'company_id', 'customer_receipt_id', 'sales_invoice_id', 'allocated_amount', 'allocation_date', 'created_at'],
    "supplier_groups": ['id', 'company_id', 'code', 'name', 'created_at', 'updated_at', 'is_active'],
    "suppliers": ['id', 'company_id', 'supplier_code', 'display_name', 'legal_name', 'supplier_group_id', 'payment_term_id', 'tax_identifier', 'phone', 'email', 'address_line_1', 'address_line_2', 'city', 'region', 'country_code', 'notes', 'created_at', 'updated_at', 'is_active'],
    "purchase_bills": ['id', 'company_id', 'bill_number', 'supplier_bill_reference', 'supplier_id', 'bill_date', 'due_date', 'currency_code', 'exchange_rate', 'status_code', 'payment_status_code', 'notes', 'subtotal_amount', 'tax_amount', 'total_amount', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at', 'contract_id', 'project_id'],
    "purchase_bill_lines": ['id', 'purchase_bill_id', 'line_number', 'description', 'quantity', 'unit_cost', 'expense_account_id', 'tax_code_id', 'line_subtotal_amount', 'line_tax_amount', 'line_total_amount', 'created_at', 'updated_at', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id'],
    "supplier_payments": ['id', 'company_id', 'payment_number', 'supplier_id', 'financial_account_id', 'payment_date', 'currency_code', 'exchange_rate', 'amount_paid', 'status_code', 'reference_number', 'notes', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at'],
    "supplier_payment_allocations": ['id', 'company_id', 'supplier_payment_id', 'purchase_bill_id', 'allocated_amount', 'allocation_date', 'created_at'],
    "financial_accounts": ['id', 'company_id', 'account_code', 'name', 'financial_account_type_code', 'gl_account_id', 'bank_name', 'bank_account_number', 'bank_branch', 'currency_code', 'created_at', 'updated_at', 'is_active'],
    "treasury_transactions": ['id', 'company_id', 'transaction_number', 'transaction_type_code', 'financial_account_id', 'transaction_date', 'currency_code', 'exchange_rate', 'total_amount', 'status_code', 'reference_number', 'description', 'notes', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at', 'contract_id', 'project_id'],
    "treasury_transaction_lines": ['id', 'treasury_transaction_id', 'line_number', 'account_id', 'line_description', 'party_type', 'party_id', 'tax_code_id', 'amount', 'created_at', 'updated_at', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id'],
    "treasury_transfers": ['id', 'company_id', 'transfer_number', 'from_financial_account_id', 'to_financial_account_id', 'transfer_date', 'currency_code', 'exchange_rate', 'amount', 'status_code', 'reference_number', 'description', 'notes', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at'],
    "bank_statement_import_batches": ['id', 'company_id', 'financial_account_id', 'file_name', 'import_source', 'statement_start_date', 'statement_end_date', 'line_count', 'notes', 'imported_at', 'imported_by_user_id'],
    "bank_statement_lines": ['id', 'company_id', 'financial_account_id', 'import_batch_id', 'line_date', 'value_date', 'description', 'reference', 'debit_amount', 'credit_amount', 'is_reconciled', 'created_at'],
    "bank_reconciliation_sessions": ['id', 'company_id', 'financial_account_id', 'statement_end_date', 'statement_ending_balance', 'status_code', 'notes', 'completed_at', 'completed_by_user_id', 'created_at', 'created_by_user_id'],
    "bank_reconciliation_matches": ['id', 'company_id', 'reconciliation_session_id', 'bank_statement_line_id', 'match_entity_type', 'match_entity_id', 'matched_amount', 'created_at'],
    "uom_categories": ['id', 'company_id', 'code', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    "units_of_measure": ['id', 'company_id', 'code', 'name', 'description', 'is_active', 'created_at', 'updated_at', 'category_id', 'ratio_to_base'],
    "item_categories": ['id', 'company_id', 'code', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    "inventory_locations": ['id', 'company_id', 'code', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    "items": ['id', 'company_id', 'item_code', 'item_name', 'item_type_code', 'unit_of_measure_code', 'inventory_cost_method_code', 'inventory_account_id', 'cogs_account_id', 'expense_account_id', 'revenue_account_id', 'purchase_tax_code_id', 'sales_tax_code_id', 'reorder_level_quantity', 'description', 'is_active', 'created_at', 'updated_at', 'unit_of_measure_id', 'item_category_id'],
    "inventory_documents": ['id', 'company_id', 'document_number', 'document_type_code', 'document_date', 'status_code', 'reference_number', 'notes', 'total_value', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at', 'updated_at', 'location_id', 'contract_id', 'project_id'],
    "inventory_document_lines": ['id', 'inventory_document_id', 'line_number', 'item_id', 'quantity', 'unit_cost', 'line_amount', 'counterparty_account_id', 'line_description', 'created_at', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id', 'transaction_uom_id', 'uom_ratio_snapshot', 'base_quantity'],
    "inventory_cost_layers": ['id', 'company_id', 'item_id', 'inventory_document_line_id', 'layer_date', 'quantity_in', 'quantity_remaining', 'unit_cost', 'created_at'],
    "asset_categories": ['id', 'company_id', 'code', 'name', 'asset_account_id', 'accumulated_depreciation_account_id', 'depreciation_expense_account_id', 'default_useful_life_months', 'default_depreciation_method_code', 'is_active', 'created_at', 'updated_at'],
    "assets": ['id', 'company_id', 'asset_number', 'asset_name', 'asset_category_id', 'acquisition_date', 'capitalization_date', 'acquisition_cost', 'salvage_value', 'useful_life_months', 'depreciation_method_code', 'status_code', 'supplier_id', 'purchase_bill_id', 'notes', 'created_at', 'updated_at'],
    "asset_depletion_profiles": ['id', 'company_id', 'asset_id', 'resource_type', 'estimated_total_units', 'unit_description', 'created_at', 'updated_at'],
    "asset_depreciation_runs": ['id', 'company_id', 'run_number', 'run_date', 'period_end_date', 'status_code', 'posted_journal_entry_id', 'posted_at', 'posted_by_user_id', 'created_at'],
    "asset_depreciation_run_lines": ['id', 'asset_depreciation_run_id', 'asset_id', 'depreciation_amount', 'accumulated_depreciation_after', 'net_book_value_after'],
    "asset_depreciation_settings": ['id', 'company_id', 'asset_id', 'declining_factor', 'switch_to_straight_line', 'expected_total_units', 'interest_rate', 'macrs_profile_id', 'macrs_convention_code', 'created_at', 'updated_at'],
    "asset_components": ['id', 'company_id', 'parent_asset_id', 'component_name', 'acquisition_cost', 'salvage_value', 'useful_life_months', 'depreciation_method_code', 'notes', 'is_active', 'created_at', 'updated_at'],
    "asset_usage_records": ['id', 'company_id', 'asset_id', 'usage_date', 'units_used', 'notes', 'created_at'],
    "asset_depreciation_pools": ['id', 'company_id', 'code', 'name', 'pool_type_code', 'depreciation_method_code', 'useful_life_months', 'is_active', 'created_at', 'updated_at'],
    "asset_depreciation_pool_members": ['id', 'pool_id', 'asset_id', 'joined_date', 'left_date'],
    "company_payroll_settings": ['company_id', 'statutory_pack_version_code', 'cnps_regime_code', 'accident_risk_class_code', 'default_pay_frequency_code', 'default_payroll_currency_code', 'overtime_policy_mode_code', 'benefit_in_kind_policy_mode_code', 'payroll_number_prefix', 'payroll_number_padding_width', 'updated_at', 'updated_by_user_id'],
    "departments": ['id', 'company_id', 'code', 'name', 'created_at', 'updated_at', 'is_active'],
    "positions": ['id', 'company_id', 'code', 'name', 'created_at', 'updated_at', 'is_active'],
    "employees": ['id', 'company_id', 'employee_number', 'display_name', 'first_name', 'last_name', 'department_id', 'position_id', 'hire_date', 'termination_date', 'phone', 'email', 'tax_identifier', 'base_currency_code', 'created_at', 'updated_at', 'is_active', 'cnps_number', 'default_payment_account_id'],
    "payroll_components": ['id', 'company_id', 'component_code', 'component_name', 'component_type_code', 'calculation_method_code', 'is_taxable', 'is_pensionable', 'expense_account_id', 'liability_account_id', 'created_at', 'updated_at', 'is_active'],
    "payroll_rule_sets": ['id', 'company_id', 'rule_code', 'rule_name', 'rule_type_code', 'effective_from', 'effective_to', 'calculation_basis_code', 'created_at', 'updated_at', 'is_active'],
    "payroll_rule_brackets": ['id', 'payroll_rule_set_id', 'line_number', 'lower_bound_amount', 'upper_bound_amount', 'rate_percent', 'fixed_amount', 'deduction_amount', 'cap_amount'],
    "employee_compensation_profiles": ['id', 'company_id', 'employee_id', 'profile_name', 'basic_salary', 'currency_code', 'effective_from', 'effective_to', 'notes', 'is_active', 'created_at', 'updated_at', 'number_of_parts'],
    "employee_component_assignments": ['id', 'company_id', 'employee_id', 'component_id', 'override_amount', 'override_rate', 'effective_from', 'effective_to', 'is_active', 'created_at', 'updated_at'],
    "payroll_input_batches": ['id', 'company_id', 'batch_reference', 'period_year', 'period_month', 'status_code', 'description', 'submitted_at', 'approved_at', 'created_at', 'updated_at'],
    "payroll_input_lines": ['id', 'company_id', 'batch_id', 'employee_id', 'component_id', 'input_amount', 'input_quantity', 'notes', 'created_at', 'updated_at'],
    "payroll_runs": ['id', 'company_id', 'run_reference', 'run_label', 'period_year', 'period_month', 'status_code', 'currency_code', 'run_date', 'payment_date', 'notes', 'calculated_at', 'approved_at', 'created_at', 'updated_at', 'posted_at', 'posted_by_user_id', 'posted_journal_entry_id'],
    "payroll_run_employees": ['id', 'company_id', 'run_id', 'employee_id', 'gross_earnings', 'taxable_salary_base', 'tdl_base', 'cnps_contributory_base', 'employer_cost_base', 'net_payable', 'total_earnings', 'total_employee_deductions', 'total_employer_contributions', 'total_taxes', 'status_code', 'calculation_notes', 'created_at', 'updated_at', 'payment_status_code', 'payment_date'],
    "payroll_run_lines": ['id', 'company_id', 'run_id', 'run_employee_id', 'employee_id', 'component_id', 'component_type_code', 'calculation_basis', 'rate_applied', 'component_amount', 'created_at', 'updated_at'],
    "payroll_run_employee_project_allocations": ['id', 'payroll_run_employee_id', 'line_number', 'contract_id', 'project_id', 'project_job_id', 'project_cost_code_id', 'allocation_basis_code', 'allocation_quantity', 'allocation_percent', 'allocated_cost_amount', 'notes', 'created_at'],
    "payroll_payment_records": ['id', 'company_id', 'run_employee_id', 'payment_date', 'amount_paid', 'payment_method_code', 'payment_reference', 'treasury_transaction_id', 'notes', 'created_by_user_id', 'updated_by_user_id', 'created_at', 'updated_at'],
    "payroll_remittance_batches": ['id', 'company_id', 'batch_number', 'payroll_run_id', 'period_start_date', 'period_end_date', 'remittance_authority_code', 'remittance_date', 'amount_due', 'amount_paid', 'status_code', 'reference', 'treasury_transaction_id', 'notes', 'created_by_user_id', 'updated_by_user_id', 'created_at', 'updated_at'],
    "payroll_remittance_lines": ['id', 'payroll_remittance_batch_id', 'line_number', 'payroll_component_id', 'liability_account_id', 'description', 'amount_due', 'amount_paid', 'status_code', 'notes', 'created_at', 'updated_at'],
    "contracts": ['id', 'company_id', 'contract_number', 'contract_title', 'customer_id', 'contract_type_code', 'currency_code', 'exchange_rate', 'base_contract_amount', 'start_date', 'planned_end_date', 'actual_end_date', 'status_code', 'billing_basis_code', 'retention_percent', 'reference_number', 'description', 'approved_at', 'approved_by_user_id', 'created_at', 'updated_at', 'created_by_user_id', 'updated_by_user_id'],
    "contract_change_orders": ['id', 'company_id', 'contract_id', 'change_order_number', 'change_order_date', 'status_code', 'change_type_code', 'description', 'contract_amount_delta', 'days_extension', 'effective_date', 'approved_at', 'approved_by_user_id', 'created_at', 'updated_at'],
    "projects": ['id', 'company_id', 'project_code', 'project_name', 'contract_id', 'customer_id', 'project_type_code', 'project_manager_user_id', 'currency_code', 'exchange_rate', 'start_date', 'planned_end_date', 'actual_end_date', 'status_code', 'budget_control_mode_code', 'notes', 'created_at', 'updated_at', 'created_by_user_id', 'updated_by_user_id'],
    "project_jobs": ['id', 'company_id', 'project_id', 'job_code', 'job_name', 'parent_job_id', 'sequence_number', 'status_code', 'start_date', 'planned_end_date', 'actual_end_date', 'allow_direct_cost_posting', 'notes', 'created_at', 'updated_at'],
    "project_cost_codes": ['id', 'company_id', 'code', 'name', 'cost_code_type_code', 'default_account_id', 'is_active', 'description', 'created_at', 'updated_at'],
    "project_budget_versions": ['id', 'company_id', 'project_id', 'version_number', 'version_name', 'version_type_code', 'status_code', 'base_version_id', 'budget_date', 'revision_reason', 'total_budget_amount', 'approved_at', 'approved_by_user_id', 'created_at', 'updated_at'],
    "project_budget_lines": ['id', 'project_budget_version_id', 'line_number', 'project_job_id', 'project_cost_code_id', 'description', 'quantity', 'unit_rate', 'line_amount', 'start_date', 'end_date', 'notes', 'created_at', 'updated_at'],
    "project_commitments": ['id', 'company_id', 'commitment_number', 'project_id', 'supplier_id', 'commitment_type_code', 'commitment_date', 'required_date', 'currency_code', 'exchange_rate', 'status_code', 'reference_number', 'notes', 'total_amount', 'approved_at', 'approved_by_user_id', 'created_at', 'updated_at'],
    "project_commitment_lines": ['id', 'project_commitment_id', 'line_number', 'project_job_id', 'project_cost_code_id', 'description', 'quantity', 'unit_rate', 'line_amount', 'notes', 'created_at', 'updated_at'],
    "audit_events": ['id', 'company_id', 'event_type_code', 'module_code', 'entity_type', 'entity_id', 'description', 'detail_json', 'actor_user_id', 'actor_display_name', 'created_at'],
}

# ===== MERGE SERVICE COLUMN LISTS ==========================================
# Extracted from backup_merge_service.py _run_merge method
MERGE_COLS = {
    "permissions": ["id", "code", "name", "module_code", "description"],
    "roles": ["id", "code", "name", "description", "is_system", "created_at", "updated_at"],
    "role_permissions": ["role_id", "permission_id"],
    "users": ["id", "username", "display_name", "email", "password_hash",
              "must_change_password", "is_active", "created_at", "updated_at",
              "last_login_at", "password_changed_at",
              "avatar_storage_path", "avatar_original_filename",
              "avatar_content_type", "avatar_sha256", "avatar_updated_at"],
    "companies": ["id", "legal_name", "display_name", "registration_number", "tax_identifier",
                  "phone", "email", "website", "sector_of_operation", "address_line_1", "address_line_2",
                  "city", "region", "country_code", "base_currency_code",
                  "logo_storage_path", "logo_original_filename", "logo_content_type", "logo_sha256",
                  "logo_updated_at", "deleted_at", "is_active", "created_at", "updated_at"],
    "company_preferences": ["id", "company_id", "date_format", "number_format",
                            "decimal_separator", "thousands_separator", "created_at", "updated_at"],
    "company_fiscal_defaults": ["id", "company_id", "fiscal_year_start_month", "fiscal_year_start_day",
                                "default_posting_grace_days", "created_at", "updated_at"],
    "company_project_preferences": ["id", "company_id", "enable_projects", "enable_contracts",
                                    "enable_job_costing", "enable_budget_control",
                                    "created_at", "updated_at"],
    "user_company_access": ["id", "user_id", "company_id", "role_scope_note",
                            "is_default_company", "granted_at", "granted_by_user_id"],
    "user_roles": ["id", "user_id", "role_id", "assigned_at", "assigned_by_user_id"],
    "payment_terms": ["id", "company_id", "name", "description", "days_due", "discount_days",
                      "discount_percent", "is_active", "created_at", "updated_at"],
    "tax_codes": ["id", "company_id", "code", "name", "rate", "tax_type",
                  "is_active", "created_at", "updated_at"],
    "document_sequences": ["id", "company_id", "sequence_type", "prefix", "next_number",
                           "pad_length", "suffix", "created_at", "updated_at"],
    "accounts": ["id", "company_id", "code", "name", "account_class_id",
                 "account_type_id", "parent_account_id",
                 "is_control_account", "control_account_type",
                 "is_active", "allow_direct_posting",
                 "opening_balance", "opening_balance_date",
                 "description", "created_at", "updated_at"],
    "account_role_mappings": ["id", "company_id", "role_code", "account_id", "created_at", "updated_at"],
    "tax_code_account_mappings": ["id", "company_id", "tax_code_id",
                                  "input_tax_account_id", "output_tax_account_id",
                                  "created_at", "updated_at"],
    "ias_income_statement_templates": ["id", "company_id", "name", "is_default", "created_at", "updated_at"],
    "ias_income_statement_sections": ["id", "template_id", "code", "label", "sort_order",
                                      "section_type", "parent_section_id"],
    "ias_income_statement_mappings": ["id", "template_id", "section_id", "account_id",
                                      "mapping_type", "created_at", "updated_at"],
    "ias_income_statement_preferences": ["id", "company_id", "template_id", "created_at", "updated_at"],
    "fiscal_years": ["id", "company_id", "name", "start_date", "end_date",
                     "status", "created_at", "updated_at"],
    "fiscal_periods": ["id", "company_id", "fiscal_year_id", "name", "period_number",
                       "start_date", "end_date", "status", "created_at", "updated_at"],
    "journal_entries": ["id", "company_id", "fiscal_period_id", "entry_number",
                        "entry_date", "description", "reference", "status",
                        "posted_at", "posted_by_user_id", "created_by_user_id",
                        "created_at", "updated_at"],
    "journal_entry_lines": ["id", "journal_entry_id", "account_id", "line_number",
                            "description", "debit_amount", "credit_amount",
                            "customer_id", "supplier_id",
                            "project_id", "cost_code_id",
                            "created_at", "updated_at"],
    "customer_groups": ["id", "company_id", "code", "name", "description",
                        "is_active", "created_at", "updated_at"],
    "customers": ["id", "company_id", "customer_group_id", "code", "name",
                  "contact_name", "email", "phone", "address_line_1", "address_line_2",
                  "city", "region", "country_code", "tax_identifier",
                  "currency_code", "payment_term_id", "control_account_id",
                  "credit_limit", "is_active", "notes",
                  "created_at", "updated_at"],
    "sales_invoices": ["id", "company_id", "customer_id", "fiscal_period_id",
                       "invoice_number", "invoice_date", "due_date",
                       "currency_code", "status",
                       "subtotal_amount", "tax_amount", "total_amount", "paid_amount",
                       "description", "reference",
                       "journal_entry_id",
                       "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "sales_invoice_lines": ["id", "sales_invoice_id", "line_number", "description",
                            "quantity", "unit_price", "discount_percent",
                            "tax_code_id", "account_id", "item_id",
                            "line_total", "tax_amount", "created_at", "updated_at"],
    "customer_receipts": ["id", "company_id", "customer_id", "fiscal_period_id",
                          "receipt_number", "receipt_date",
                          "currency_code", "amount", "status",
                          "reference", "notes",
                          "journal_entry_id",
                          "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "customer_receipt_allocations": ["id", "receipt_id", "invoice_id",
                                    "allocated_amount", "created_at", "updated_at"],
    "supplier_groups": ["id", "company_id", "code", "name", "description",
                        "is_active", "created_at", "updated_at"],
    "suppliers": ["id", "company_id", "supplier_group_id", "code", "name",
                  "contact_name", "email", "phone", "address_line_1", "address_line_2",
                  "city", "region", "country_code", "tax_identifier",
                  "currency_code", "payment_term_id", "control_account_id",
                  "credit_limit", "is_active", "notes",
                  "created_at", "updated_at"],
    "purchase_bills": ["id", "company_id", "supplier_id", "fiscal_period_id",
                       "bill_number", "supplier_reference",
                       "bill_date", "due_date",
                       "currency_code", "status",
                       "subtotal_amount", "tax_amount", "total_amount", "paid_amount",
                       "description", "reference",
                       "journal_entry_id",
                       "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "purchase_bill_lines": ["id", "purchase_bill_id", "line_number", "description",
                            "quantity", "unit_price", "discount_percent",
                            "tax_code_id", "account_id", "item_id",
                            "line_total", "tax_amount", "created_at", "updated_at"],
    "supplier_payments": ["id", "company_id", "supplier_id", "fiscal_period_id",
                          "payment_number", "payment_date",
                          "currency_code", "amount", "status",
                          "reference", "notes",
                          "journal_entry_id",
                          "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "supplier_payment_allocations": ["id", "payment_id", "bill_id",
                                    "allocated_amount", "created_at", "updated_at"],
    "financial_accounts": ["id", "company_id", "account_id", "code", "name",
                           "account_type", "currency_code",
                           "bank_name", "bank_branch", "bank_account_number", "iban", "swift_code",
                           "opening_balance", "opening_balance_date",
                           "is_active", "created_at", "updated_at"],
    "treasury_transactions": ["id", "company_id", "financial_account_id", "fiscal_period_id",
                              "transaction_number", "transaction_date", "value_date",
                              "transaction_type", "amount", "currency_code",
                              "description", "reference", "status",
                              "journal_entry_id", "bank_statement_line_id",
                              "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "treasury_transaction_lines": ["id", "treasury_transaction_id", "account_id", "line_number",
                                   "description", "debit_amount", "credit_amount",
                                   "created_at", "updated_at"],
    "treasury_transfers": ["id", "company_id", "from_financial_account_id", "to_financial_account_id",
                           "fiscal_period_id", "transfer_number", "transfer_date",
                           "amount", "currency_code", "description", "reference", "status",
                           "journal_entry_id",
                           "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "bank_statement_import_batches": ["id", "company_id", "financial_account_id", "imported_at",
                                     "source_filename", "record_count", "created_at"],
    "bank_statement_lines": ["id", "company_id", "financial_account_id", "import_batch_id",
                             "transaction_date", "value_date", "description",
                             "reference", "amount", "running_balance",
                             "match_status", "created_at", "updated_at"],
    "bank_reconciliation_sessions": ["id", "company_id", "financial_account_id", "fiscal_period_id",
                                     "statement_end_date", "statement_closing_balance",
                                     "status", "closed_at", "created_at", "updated_at"],
    "bank_reconciliation_matches": ["id", "reconciliation_session_id", "bank_statement_line_id",
                                    "treasury_transaction_id",
                                    "match_type", "match_amount", "created_at", "updated_at"],
    "uom_categories": ["id", "name", "description", "is_active", "created_at", "updated_at"],
    "units_of_measure": ["id", "category_id", "code", "name", "symbol",
                         "is_base_unit", "conversion_factor", "is_active",
                         "created_at", "updated_at"],
    "item_categories": ["id", "company_id", "code", "name", "description",
                        "is_active", "created_at", "updated_at"],
    "inventory_locations": ["id", "company_id", "code", "name", "description",
                            "is_active", "created_at", "updated_at"],
    "items": ["id", "company_id", "item_category_id", "code", "name",
              "description", "uom_id", "item_type",
              "sales_price", "purchase_price",
              "sales_account_id", "purchase_account_id", "inventory_account_id",
              "tax_code_id", "is_active",
              "created_at", "updated_at"],
    "inventory_documents": ["id", "company_id", "fiscal_period_id",
                            "document_number", "document_type", "document_date",
                            "from_location_id", "to_location_id",
                            "reference", "description", "status",
                            "journal_entry_id",
                            "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "inventory_document_lines": ["id", "inventory_document_id", "item_id", "uom_id",
                                 "quantity", "unit_cost", "total_cost", "line_number",
                                 "description", "created_at", "updated_at"],
    "inventory_cost_layers": ["id", "company_id", "item_id", "location_id",
                              "document_line_id",
                              "entry_date", "quantity", "unit_cost",
                              "remaining_quantity", "created_at"],
    "asset_categories": ["id", "company_id", "code", "name", "description",
                         "asset_account_id", "accumulated_depreciation_account_id",
                         "depreciation_expense_account_id", "disposal_gain_account_id",
                         "disposal_loss_account_id",
                         "default_depreciation_method_id",
                         "default_useful_life_years",
                         "is_active", "created_at", "updated_at"],
    "assets": ["id", "company_id", "asset_category_id",
               "asset_number", "name", "description",
               "acquisition_date", "acquisition_cost",
               "residual_value", "useful_life_years",
               "depreciation_method_id",
               "status", "disposal_date", "disposal_proceeds",
               "location", "serial_number", "notes",
               "created_at", "updated_at"],
    "asset_depletion_profiles": ["id", "company_id", "asset_id",
                                 "resource_type", "estimated_total_units", "unit_description",
                                 "created_at", "updated_at"],
    "asset_depreciation_runs": ["id", "company_id", "fiscal_period_id",
                                "run_date", "status", "description",
                                "journal_entry_id",
                                "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "asset_depreciation_run_lines": ["id", "depreciation_run_id", "asset_id",
                                     "depreciation_amount", "accumulated_depreciation",
                                     "net_book_value", "created_at"],
    "asset_depreciation_settings": ["id", "company_id", "asset_id",
                                    "depreciation_method_id", "useful_life_years",
                                    "residual_value", "created_at", "updated_at"],
    "asset_components": ["id", "asset_id", "name", "description",
                         "acquisition_cost", "is_active",
                         "created_at", "updated_at"],
    "asset_usage_records": ["id", "asset_id", "usage_date",
                            "units_used", "notes", "created_at"],
    "asset_depreciation_pools": ["id", "company_id", "name", "description",
                                 "depreciation_method_id", "pool_rate",
                                 "is_active", "created_at", "updated_at"],
    "asset_depreciation_pool_members": ["id", "pool_id", "asset_id", "added_at"],
    "company_payroll_settings": ["id", "company_id", "payroll_currency", "social_security_rate_employer",
                                 "social_security_rate_employee", "pension_rate_employer",
                                 "pension_rate_employee", "work_days_per_month",
                                 "created_at", "updated_at"],
    "departments": ["id", "company_id", "code", "name",
                    "is_active", "created_at", "updated_at"],
    "positions": ["id", "company_id", "department_id", "code", "name",
                  "is_active", "created_at", "updated_at"],
    "employees": ["id", "company_id", "employee_number", "first_name", "last_name",
                  "gender", "date_of_birth", "hire_date", "termination_date",
                  "department_id", "position_id",
                  "email", "phone", "address",
                  "national_id", "passport_number",
                  "bank_name", "bank_account_number",
                  "employment_type", "is_active",
                  "created_at", "updated_at"],
    "payroll_components": ["id", "company_id", "code", "name", "component_type",
                           "calculation_base", "amount", "rate",
                           "account_id", "is_taxable", "is_pensionable",
                           "is_active", "created_at", "updated_at"],
    "payroll_rule_sets": ["id", "company_id", "name", "rule_type",
                          "is_active", "created_at", "updated_at"],
    "payroll_rule_brackets": ["id", "rule_set_id", "lower_bound", "upper_bound",
                              "rate", "fixed_amount", "created_at", "updated_at"],
    "employee_compensation_profiles": ["id", "company_id", "employee_id", "effective_date",
                                       "basic_salary", "currency_code",
                                       "created_at", "updated_at"],
    "employee_component_assignments": ["id", "company_id", "employee_id", "component_id",
                                       "override_amount", "override_rate",
                                       "effective_date", "end_date",
                                       "is_active", "created_at", "updated_at"],
    "payroll_input_batches": ["id", "company_id", "batch_number", "period_start", "period_end",
                              "status", "description",
                              "created_by_user_id", "created_at", "updated_at"],
    "payroll_input_lines": ["id", "batch_id", "employee_id", "component_id",
                            "amount", "notes", "created_at", "updated_at"],
    "payroll_runs": ["id", "company_id", "fiscal_period_id",
                     "run_number", "pay_period_start", "pay_period_end",
                     "status", "description",
                     "journal_entry_id",
                     "posted_at", "created_by_user_id", "created_at", "updated_at"],
    "payroll_run_employees": ["id", "payroll_run_id", "employee_id",
                              "gross_pay", "net_pay", "total_deductions",
                              "employer_contributions",
                              "status", "created_at", "updated_at"],
    "payroll_run_employee_project_allocations": ["id", "payroll_run_employee_id", "project_id",
                                                 "allocation_percent", "created_at"],
    "payroll_run_lines": ["id", "payroll_run_employee_id", "component_id",
                          "amount", "is_employer_contribution",
                          "created_at", "updated_at"],
    "payroll_payment_records": ["id", "company_id", "payroll_run_id", "employee_id",
                                "payment_date", "amount", "payment_method",
                                "reference", "status",
                                "created_at", "updated_at"],
    "payroll_remittance_batches": ["id", "company_id", "payroll_run_id",
                                   "remittance_type", "due_date", "amount",
                                   "status", "reference",
                                   "created_at", "updated_at"],
    "payroll_remittance_lines": ["id", "remittance_batch_id", "employee_id",
                                 "component_id", "amount", "created_at"],
    "contracts": ["id", "company_id", "contract_number", "name",
                  "customer_id", "contract_date", "start_date", "end_date",
                  "currency_code", "original_value", "revised_value",
                  "status", "description",
                  "created_by_user_id", "created_at", "updated_at"],
    "contract_change_orders": ["id", "contract_id", "change_order_number",
                               "description", "amount", "approved_date",
                               "status", "created_at", "updated_at"],
    "projects": ["id", "company_id", "contract_id",
                 "project_number", "name", "description",
                 "customer_id", "start_date", "end_date",
                 "status", "budget_amount",
                 "project_manager_employee_id",
                 "created_by_user_id", "created_at", "updated_at"],
    "project_jobs": ["id", "project_id", "code", "name",
                     "description", "budget_amount",
                     "is_active", "created_at", "updated_at"],
    "project_cost_codes": ["id", "company_id", "code", "name",
                           "description", "account_id",
                           "is_active", "created_at", "updated_at"],
    "project_budget_versions": ["id", "project_id", "version_number", "name",
                                "is_current", "status", "approved_at",
                                "created_at", "updated_at"],
    "project_budget_lines": ["id", "budget_version_id", "job_id", "cost_code_id",
                             "description", "budgeted_amount",
                             "created_at", "updated_at"],
    "project_commitments": ["id", "company_id", "project_id",
                            "commitment_number", "commitment_type",
                            "supplier_id", "description",
                            "commitment_date", "amount", "currency_code",
                            "status", "reference",
                            "created_by_user_id", "created_at", "updated_at"],
    "project_commitment_lines": ["id", "commitment_id", "job_id", "cost_code_id",
                                 "description", "amount", "created_at", "updated_at"],
    "audit_events": ["id", "company_id", "user_id", "event_type",
                     "entity_type", "entity_id", "entity_label",
                     "description", "metadata_json", "occurred_at"],
}

# ===== AUDIT =====
CRITICAL_ISSUES = []
WARNINGS = []

for table_name in sorted(set(list(DB_SCHEMA.keys()) + list(MERGE_COLS.keys()))):
    db_cols = set(DB_SCHEMA.get(table_name, []))
    merge_cols = set(MERGE_COLS.get(table_name, []))
    
    if not merge_cols:
        continue  # Intentionally excluded table
    
    # Columns merge tries to write but don't exist in DB
    phantom = merge_cols - db_cols
    if phantom:
        CRITICAL_ISSUES.append(f"FATAL {table_name}: merge writes columns NOT in DB: {sorted(phantom)}")
    
    # Columns in DB but not in merge (data loss)
    missing = db_cols - merge_cols
    if missing:
        # Filter out 'id' for tables that have no id in merge (junction tables)
        WARNINGS.append(f"DATA_LOSS {table_name}: DB columns NOT in merge: {sorted(missing)}")

print("=" * 80)
print("BACKUP MERGE AUDIT RESULTS")
print("=" * 80)
print()

if CRITICAL_ISSUES:
    print(f"### CRITICAL ({len(CRITICAL_ISSUES)}) — INSERT WILL FAIL ###")
    for issue in CRITICAL_ISSUES:
        print(f"  {issue}")
    print()

if WARNINGS:
    print(f"### DATA LOSS WARNINGS ({len(WARNINGS)}) — COLUMNS SKIPPED ###")
    for w in WARNINGS:
        print(f"  {w}")
    print()

if not CRITICAL_ISSUES and not WARNINGS:
    print("ALL CLEAN — no column mismatches found")
