#!/usr/bin/env python3
"""
Generate a signed Seeker Accounting license key.

Requires the Ed25519 private key generated by generate_license_keypair.py.

Key format:
  SEEKER-{base64url_no_padding(17_byte_payload + 64_byte_ed25519_signature)}

Payload layout (17 bytes, big-endian):
  [0]     edition  : uint8  — always 1 (standard)
  [1..4]  issued_at: uint32 — Unix timestamp (UTC)
  [5..8]  expires_at: uint32 — Unix timestamp (UTC)
  [9..16] nonce    : 8 random bytes

Usage:
  python scripts/generate_license_key.py \\
      --private-key ./keys/seeker_license_private.pem \\
      --expiry-days 365 \\
      [--email customer@example.com]
"""
from __future__ import annotations

import argparse
import base64
import os
import struct
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Issue a signed Seeker Accounting license key.")
    parser.add_argument(
        "--private-key",
        required=True,
        help="Path to the Ed25519 private key PEM file.",
    )
    parser.add_argument(
        "--expiry-days",
        type=int,
        default=365,
        help="Number of days until the license expires (default: 365).",
    )
    parser.add_argument(
        "--email",
        default="",
        help="Customer email (informational only, printed alongside the key).",
    )
    parser.add_argument(
        "--edition",
        type=int,
        default=1,
        help="License edition byte (default: 1 = standard).",
    )
    args = parser.parse_args()

    private_key_path = Path(args.private_key).resolve()
    if not private_key_path.exists():
        print(f"ERROR: Private key file not found: {private_key_path}")
        sys.exit(1)

    try:
        from cryptography.hazmat.primitives.serialization import load_pem_private_key
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    except ImportError:
        print("ERROR: 'cryptography' package is not installed. Run: pip install cryptography")
        sys.exit(1)

    pem_data = private_key_path.read_bytes()
    private_key = load_pem_private_key(pem_data, password=None)
    if not isinstance(private_key, Ed25519PrivateKey):
        print("ERROR: The provided key is not an Ed25519 private key.")
        sys.exit(1)

    now = datetime.now(tz=timezone.utc)
    expires = now + timedelta(days=args.expiry_days)

    issued_ts = int(now.timestamp())
    expires_ts = int(expires.timestamp())
    nonce = os.urandom(8)

    # Pack 17-byte payload
    payload = struct.pack("!BII8s", args.edition, issued_ts, expires_ts, nonce)
    assert len(payload) == 17, "Payload size mismatch"

    # Sign
    signature = private_key.sign(payload)
    assert len(signature) == 64, "Signature size mismatch"

    # Encode: base64url without padding
    raw = payload + signature
    encoded = base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")
    license_key = f"SEEKER-{encoded}"

    print("=" * 60)
    print("LICENSE KEY GENERATED")
    print("=" * 60)
    if args.email:
        print(f"Customer  : {args.email}")
    print(f"Issued    : {now.strftime('%Y-%m-%d')}")
    print(f"Expires   : {expires.strftime('%Y-%m-%d')} ({args.expiry_days} days)")
    print(f"Edition   : {args.edition}")
    print()
    print("License key:")
    print(license_key)
    print()
    print(f"Key length: {len(license_key)} characters")


if __name__ == "__main__":
    main()
