"""State keys for the Period Reopen Wizard."""
KEY_PERIOD_ID = "period_id"
KEY_PERIOD_CODE = "period_code"
KEY_PERIOD_NAME = "period_name"
KEY_PREVIOUS_STATUS = "previous_status_code"
KEY_REASON = "reason"
KEY_REASON_ACKNOWLEDGED = "reason_acknowledged"
KEY_REOPEN_RESULT_NEW_STATUS = "reopen_result_new_status"
KEY_REOPEN_RESULT_PERIOD_ID = "reopen_result_period_id"
