APP_NAME = "Seeker Accounting"
ORGANIZATION_NAME = "Seeker Accounting"
WINDOW_TITLE = "Seeker Accounting"

DEFAULT_ENVIRONMENT = "development"
DEFAULT_THEME_NAME = "light"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_CURRENT_USER_DISPLAY_NAME = "Seeker Operator"

DATABASE_FILENAME = "seeker_accounting.db"
LOG_FILENAME = "seeker_accounting.log"

WINDOW_DEFAULT_WIDTH = 1360
WINDOW_DEFAULT_HEIGHT = 860
WINDOW_MINIMUM_RATIO = 0.75
WINDOW_MIN_WIDTH = int(WINDOW_DEFAULT_WIDTH * WINDOW_MINIMUM_RATIO)
WINDOW_MIN_HEIGHT = int(WINDOW_DEFAULT_HEIGHT * WINDOW_MINIMUM_RATIO)
