from __future__ import annotations

from enum import StrEnum


class ModuleCode(StrEnum):
    DASHBOARD = "dashboard"
    COMPANIES = "companies"
    CUSTOMERS = "customers"
    SUPPLIERS = "suppliers"
    PAYMENT_TERMS = "payment_terms"
    TAX_CODES = "tax_codes"
    DOCUMENT_SEQUENCES = "document_sequences"
    CHART_OF_ACCOUNTS = "chart_of_accounts"
    ACCOUNT_ROLE_MAPPINGS = "account_role_mappings"
    FISCAL_PERIODS = "fiscal_periods"
    JOURNALS = "journals"
    CUSTOMER_QUOTES = "customer_quotes"
    SALES_ORDERS = "sales_orders"
    SALES_CREDIT_NOTES = "sales_credit_notes"
    SALES_INVOICES = "sales_invoices"
    CUSTOMER_RECEIPTS = "customer_receipts"
    PURCHASE_ORDERS = "purchase_orders"
    PURCHASE_CREDIT_NOTES = "purchase_credit_notes"
    PURCHASE_BILLS = "purchase_bills"
    SUPPLIER_PAYMENTS = "supplier_payments"
    FINANCIAL_ACCOUNTS = "financial_accounts"
    TREASURY_TRANSACTIONS = "treasury_transactions"
    TREASURY_TRANSFERS = "treasury_transfers"
    STATEMENT_LINES = "statement_lines"
    BANK_RECONCILIATION = "bank_reconciliation"
    UOM_CATEGORIES = "uom_categories"
    UNITS_OF_MEASURE = "units_of_measure"
    ITEM_CATEGORIES = "item_categories"
    INVENTORY_LOCATIONS = "inventory_locations"
    ITEMS = "items"
    INVENTORY_DOCUMENTS = "inventory_documents"
    STOCK_POSITION = "stock_position"
    ASSET_CATEGORIES = "asset_categories"
    ASSETS = "assets"
    DEPRECIATION_RUNS = "depreciation_runs"
    CONTRACTS = "contracts"
    PROJECTS = "projects"
    PAYROLL_SETUP = "payroll_setup"
    PAYROLL_CALCULATION = "payroll_calculation"
    PAYROLL_ACCOUNTING = "payroll_accounting"
    PAYROLL_OPERATIONS = "payroll_operations"
    REPORTS = "reports"
    PROJECT_VARIANCE_ANALYSIS = "project_variance_analysis"
    CONTRACT_SUMMARY = "contract_summary"
    ADMINISTRATION = "administration"
    ORGANISATION_SETTINGS = "organisation_settings"
