from __future__ import annotations

from typing import Final


class AppErrorCode:
    """Structured error codes for guided workflow and prerequisite blockers."""

    MISSING_FISCAL_PERIOD: Final[str] = "MISSING_FISCAL_PERIOD"
    LOCKED_FISCAL_PERIOD: Final[str] = "LOCKED_FISCAL_PERIOD"
    MISSING_DOCUMENT_SEQUENCE: Final[str] = "MISSING_DOCUMENT_SEQUENCE"
    MISSING_ACCOUNT_ROLE_MAPPING: Final[str] = "MISSING_ACCOUNT_ROLE_MAPPING"
    MISSING_TAX_CODE_ACCOUNT_MAPPING: Final[str] = "MISSING_TAX_CODE_ACCOUNT_MAPPING"
    MISSING_FINANCIAL_ACCOUNT_GL_MAPPING: Final[str] = "MISSING_FINANCIAL_ACCOUNT_GL_MAPPING"
    MISSING_INVENTORY_ACCOUNT_MAPPING: Final[str] = "MISSING_INVENTORY_ACCOUNT_MAPPING"
    MISSING_ASSET_POSTING_ACCOUNT_MAPPING: Final[str] = "MISSING_ASSET_POSTING_ACCOUNT_MAPPING"
    REFERENCE_DATA_LOAD_FAILED: Final[str] = "REFERENCE_DATA_LOAD_FAILED"
    UNKNOWN_WORKFLOW_BLOCKER: Final[str] = "UNKNOWN_WORKFLOW_BLOCKER"


ALL_APP_ERROR_CODES: Final[tuple[str, ...]] = (
    AppErrorCode.MISSING_FISCAL_PERIOD,
    AppErrorCode.LOCKED_FISCAL_PERIOD,
    AppErrorCode.MISSING_DOCUMENT_SEQUENCE,
    AppErrorCode.MISSING_ACCOUNT_ROLE_MAPPING,
    AppErrorCode.MISSING_TAX_CODE_ACCOUNT_MAPPING,
    AppErrorCode.MISSING_FINANCIAL_ACCOUNT_GL_MAPPING,
    AppErrorCode.MISSING_INVENTORY_ACCOUNT_MAPPING,
    AppErrorCode.MISSING_ASSET_POSTING_ACCOUNT_MAPPING,
    AppErrorCode.REFERENCE_DATA_LOAD_FAILED,
    AppErrorCode.UNKNOWN_WORKFLOW_BLOCKER,
)
